import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { read_csv } from 'danfojs';
import Table from '../components/Table';
import { useState } from 'react';
import Button from '@mui/material/Button';
import { styled } from '@mui/material/styles';

const Input = styled('input')({
  display: 'none',
});

const Home: NextPage = () => {
  const [columns, setColumns] = useState<Array<string>>([]);
  const [data, setData] = useState<Array<Array<string>>>([[]]);

  const handleInputFileChange: React.ChangeEventHandler<HTMLInputElement> = (
    e
  ) => {
    const file = e.target.files?.[0];
    const url = URL.createObjectURL(file);
    read_csv(url, {}).then((df) => {
      const columns_ = df.columns;
      setColumns(columns_);
      const data_ = df.values as Array<Array<string>>;
      setData(data_);
    });
    console.log(`choose a file, the file name is ${file?.name}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <label htmlFor="contained-button-file">
            <Input
              accept=".csv"
              id="contained-button-file"
              type="file"
              onChange={handleInputFileChange}
            />
            <Button variant="contained" component="span">
              Upload
            </Button>
          </label>
        </div>
        <Table columns={columns} data={data} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
