import { DataFrame, read_csv } from 'danfojs';
import { either, taskEither } from 'fp-ts';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import ChooseFile from '../components/ChooseFile';
import Table from '../components/Table';
import styles from '../styles/Home.module.css';

const readCsv = (url: string): taskEither.TaskEither<Error, DataFrame> =>
  taskEither.tryCatch(
    () => read_csv(url, {}),
    (err) => new Error(String(err))
  );

const Home: NextPage = () => {
  const [columns, setColumns] = useState<Array<string>>([]);
  const [data, setData] = useState<Array<Array<string>>>([[]]);

  const handleInputFileChange: React.ChangeEventHandler<HTMLInputElement> = (
    e
  ) => {
    const file = e.target.files?.[0];
    const url = URL.createObjectURL(file);
    readCsv(url)().then(
      either.fold(
        // TODO: 读取文件失败, 打印错误到控制台. 未来需要修改该方法在界面提醒用户操作失败
        console.error,
        // 读取文件成功
        (df) => {
          setColumns(df.columns);
          setData(df.values as Array<Array<string>>);
        }
      )
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <ChooseFile
            id="ChooseFile-vacancy"
            handleInputFileChange={handleInputFileChange}
          />
        </div>
        <Table columns={columns} data={data} />
      </main>
    </div>
  );
};

export default Home;
